name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Kubectl
      run: curl -L https://storage.googleapis.com/kubernetes-release/release/v1.17.2/bin/linux/amd64/kubectl > $(go env GOPATH)/bin/kubectl && chmod +x $(go env GOPATH)/bin/kubectl

    - name: Kind
      run: curl -L "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64" > $(go env GOPATH)/bin/kind && chmod +x $(go env GOPATH)/bin/kind

    - name: GolangCi-lint
      run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
          sh -s -- -b $(go env GOPATH)/bin v1.31.0

    - name: Kustomize
      run: curl -s "https://raw.githubusercontent.com/\
          kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" > install_kustomize.sh && chmod +x install_kustomize.sh && ls -al
      shell: bash

    - name: Setup-clusters
      run: ./ci/setup_clusters.sh

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: test
        run: ./ci/test.sh
      - name: build
        run: ./ci/build.sh
      - name: e2e
        run: ./ci/e2e.sh

#   release:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: release
#         run: ./ci/release.sh
        

    
